name = "telegram-ranking-bot"
main = "index.js"
compatibility_date = "2024-08-12"

[[kv_namespaces]]
binding = "MESSAGE_COUNT"
id = "26223536f94647148cda73c3c7e15e74"

[triggers]
crons = ["0 20 * * *"]  # 19:30 UTC = 23:00 IRST
